### ISSUE TITLE
Differentiate data source on SRKW occurrence map

### ISSUE THREAD

**Issue by scottveirs** [liu-zoe/orcasalmon#7]
Now that you are visualizing an analyzing data from both Acartia and The Whale Museum, it would be edifying and consistent with the Acartia Creative Commons attribution guidance to indicate which data points came from which data source.

One idea for how to do this: use circular markers as you have for Acartia data points, but some other shape or The Whale Museum points.

Additionally, in the `Data source` notes below the SRKW occurrence map, you could indicate the date range for each data source parenthetically after each source name, e.g. `Acartia (2018-present) and The Whale Museum (1973-2020). (BTW: it looks like the link to TWM is relative -- `https://salmonorca.fly.dev/whalemuseum.org` -- when it should be absolute (and maybe open in a new tab/window?)...)

**Comment by liu-zoe** [comment]
Good idea! I'll add that to the to-list. And thanks for catching the bad link to TWM. I'll fix that soon!

**Comment by liu-zoe** [comment]
Date range for each data source are added to the footnote and the TWM link fixed. To indicate the source of data on the map, I ended up with adding the source as text to the hover text for the dots. Customized symbols can be added but we will have to give up the color scale indicating time of sighting because marker color customization only work on circles. 

<img width="836" alt="Screenshot 2023-09-20 at 10 27 04 AM" src="https://github.com/liu-zoe/orcasalmon/assets/7928761/6bde8a03-51e4-4734-aa5f-4a48cc8f64ce">

**Comment by scottveirs** [comment]
The mouseover works great for me, @liu-zoe , and with the link in the footer meets the Creative Commons guidance for Acartia points.

It is fascinating to see data gaps in both sources by looking at years like 2019 (when Acartia was just spinning up) and 2020. In some ways they seem complimentary (many TWM points coming in from the Soundwatch boat during days when SRKWs present, I think, whereas most Acartia points are land-based observations or acoustic detections at night.

It's going to be interesting to create similar visualizations of data distribution by data_source for Bigg's (which I think TWM logs?) and other cetaceans, and to contemplate how to fill gaps for each (not to mention for pinnipeds, marine birds, etc.)!

**Comment by liu-zoe** [comment]
Good to know that it worked! I agree that the TWM and Acartia really do compliment each other and give us a much more robust view of the presence!
